## Build container
FROM ubuntu AS builder

RUN apt update && apt install -y git nodejs npm ruby-compass
RUN npm install -g npx
RUN git clone -b embedded-2.3.1 --single-branch https://github.com/notalib/lyt.git
ARG DODP_HOST=m.nota.dk
ARG DRUPAL_HOST=nota.dk 
ARG PLAY_HOST=afspil.nota.dk
RUN cd /lyt/src/config; sed -e "s#\(originDomain: \"\)nota\.dk\(\"\)#\1$PLAY_HOST\2#" -e "s#//m\.nota\.dk#//$DODP_HOST#" -e "s#//nota\.dk#//$DRUPAL_HOST#" config.coffee  > config.coffee.new; rm config.coffee; mv config.coffee.new config.coffee
RUN cat /lyt/src/config/config.coffee
RUN cd lyt && npm install && npx cake app


## Webserver with LYT2
FROM nginx:1.15.3-alpine

COPY --from=builder /lyt/build /usr/share/nginx/html/embedded
